const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const origin=process.env.QA_ORIGIN||'http://127.0.0.1:8765',root=process.env.QA_APP_PATH||'nth-shelf-current',comic=process.env.QA_COMIC_PATH||'manga-chapter31',out=process.env.QA_OUTPUT||'/tmp/nth-shelf-test59';fs.mkdirSync(out,{recursive:true});
const target=Number(process.env.QA_PAGE||2),qa=require('./batch-anchors.json')[target];
function inside(q,x,y){let v=false;for(let i=0,j=q.length-1;i<q.length;j=i++){const a=q[i],b=q[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])v=!v;}return v;}

for(const frame of qa.frames){frame.dense=[];const [x,y,r]=frame.denseSquare;for(let Y=y-r;Y<=y+r;Y+=3)for(let X=x-r;X<=x+r;X+=3)frame.dense.push([X,Y]);}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN,headless:true,args:['--no-sandbox']});try{const page=await b.newPage({viewport:{width:412,height:915},deviceScaleFactor:2.625,isMobile:true,hasTouch:true,serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/'+root+'/');

const initial=await page.evaluate(async({comic,target})=>{const blob=await(await fetch('/'+comic+'/'+('page-'+String(target).padStart(2,'0')+'.png'))).blob();await LongboxDB.putPage('p49-test59',0,blob);await LongboxDB.addComic({id:'p49-test59',title:'Page '+target+' test',pageCount:1,lastPage:0,bookmarks:[],addedAt:Date.now(),readMode:'single',theme:'dark'});ShelfGuide.finish();ShelfGuide.seen.single=true;await LongboxApp.openReader('p49-test59');await Reader._panelDetection?.promise;Reader.panelZoomEnabled=true;window.captures=[];const zoom=Reader.zoomToPanel;Reader.zoomToPanel=function(p,...args){captures.push(JSON.parse(JSON.stringify(p)));return zoom.call(this,p,...args)};return{panels:Reader.currentPanels,deck:Reader.turnPageMode?.book instanceof NthPageDeck};},{comic,target});fs.writeFileSync(out+'/reader-initial.json',JSON.stringify(initial));console.log('current',initial.panels.length,'deck',initial.deck);assert.equal(initial.panels.length,qa.count);assert.equal(qa.frames.length,qa.count);
const ownership=await page.evaluate(frames=>frames.flatMap(f=>f.points.map(([x,y])=>({name:f.name,expected:f.owner,x,y,got:Reader.currentPanels.indexOf(Reader.findPanelAt(x/616,y/900))}))),qa.frames);console.log('ownership',ownership.length,ownership.filter(r=>r.expected!==r.got));assert(ownership.every(r=>r.expected===r.got));
const touches=[];for(const frame of qa.frames.filter(f=>!process.env.QA_FRAME||f.name===process.env.QA_FRAME))for(let i=0;i<frame.points.length;i++){
 await page.evaluate(()=>Reader.resetZoom({animate:false}));await page.waitForTimeout(80);const [x,y]=frame.points[i];const pos=await page.evaluate(([x,y])=>{const r=Reader.getPanelImageContext().rect;return{x:r.left+x/616*r.width,y:r.top+y/900*r.height,n:captures.length}},[x,y]);console.log("tap",frame.name,i,x,y,pos.x,pos.y);await page.touchscreen.tap(pos.x,pos.y);await page.waitForFunction(n=>captures.length>n,pos.n,{timeout:20000}).catch(async e=>{await page.screenshot({path:out+'/timeout.png'});console.log(await page.evaluate(()=>({scale:Reader.scale,overlay:Reader.panelOverlayActive,focus:Reader.focusMode,captures:captures.length,mode:Reader.mode})));throw e;});await page.waitForFunction(()=>Reader.panelOverlayActive&&!!Reader.els.panelOverlay?.querySelector('canvas'),null,{timeout:20000});
 const result=await page.evaluate(({owner,points,dense,foreign,extras})=>{const panel=captures.at(-1),original=Reader.currentPanels[owner],canvas=Reader.els.panelOverlay.querySelector('canvas'),meta=Reader.panelFocusMeta.panel;const q=p=>p._outline||p._quad||p._contours;return{same:JSON.stringify(q(panel))===JSON.stringify(q(original)),focusSame:JSON.stringify(q(meta))===JSON.stringify(q(original)),geometry:Reader.els.panelOverlay.dataset.geometry,size:[canvas.width,canvas.height],foreignAlpha:foreign.map(([x,y])=>canvas.getContext('2d').getImageData(Math.round((x/616-original.x)/original.w*canvas.width),Math.round((y/900-original.y)/original.h*canvas.height),1,1).data[3]),extraAlpha:extras.map(([x,y])=>canvas.getContext('2d').getImageData(Math.round((x/616-original.x)/original.w*canvas.width),Math.round((y/900-original.y)/original.h*canvas.height),1,1).data[3]),denseOpaque:dense.map(([x,y])=>{const X=Math.round((x/616-original.x)/original.w*canvas.width),Y=Math.round((y/900-original.y)/original.h*canvas.height);return canvas.getContext('2d').getImageData(X,Y,1,1).data[3];}),opaque:points.map(([x,y])=>{const X=Math.round((x/616-original.x)/original.w*canvas.width),Y=Math.round((y/900-original.y)/original.h*canvas.height);return canvas.getContext('2d').getImageData(X,Y,1,1).data[3];})};},{owner:frame.owner,points:frame.points,dense:i===0?frame.dense:[],foreign:frame.foreign||[],extras:frame.extras||[]});assert(result.foreignAlpha.every(a=>a===0));assert(result.extraAlpha.every(a=>a===255),JSON.stringify({name:frame.name,extraAlpha:result.extraAlpha}));assert(result.same&&result.focusSame,JSON.stringify({frame,i,result}));assert(result.denseOpaque.every(a=>a===255),JSON.stringify({name:frame.name,denseMissing:result.denseOpaque.filter(a=>a!==255).length}));assert(result.opaque.every(a=>a===255),JSON.stringify({frame,i,result}));touches.push({name:frame.name,x,y,...result});await page.waitForTimeout(300);if(!i)await page.screenshot({path:out+'/render-'+frame.name+'.png'});
}fs.writeFileSync(out+'/reader-report.json',JSON.stringify({ownership,touches,errors},null,2));console.log('PASS touches',touches.length,'errors',errors);assert.equal(errors.length,0);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
