const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const origin=process.env.QA_ORIGIN||'http://127.0.0.1:8765',root=process.env.QA_APP_PATH||'nth-shelf-current',comic=process.env.QA_COMIC_PATH||'comic-wolverine-1000',out=process.env.QA_OUTPUT||'/tmp/nth-shelf-test48';fs.mkdirSync(out,{recursive:true});
const qa=require('./page43-anchors.json');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN,headless:true,args:['--no-sandbox']});try{const page=await b.newPage({viewport:{width:412,height:915},deviceScaleFactor:2.625,isMobile:true,hasTouch:true,serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/'+root+'/');
const initial=await page.evaluate(async(comic)=>{const blob=await(await fetch('/'+comic+'/'+encodeURIComponent('Wolverine (2010-2012) 1000-042.jpg'))).blob();await LongboxDB.putPage('p43-test48',0,blob);await LongboxDB.addComic({id:'p43-test48',title:'Page 43 test',pageCount:1,lastPage:0,bookmarks:[],addedAt:Date.now(),readMode:'single',theme:'dark'});ShelfGuide.finish();ShelfGuide.seen.single=true;await LongboxApp.openReader('p43-test48');await Reader._panelDetection?.promise;Reader.panelZoomEnabled=true;window.captures=[];const zoom=Reader.zoomToPanel;Reader.zoomToPanel=function(p,...args){captures.push(JSON.parse(JSON.stringify(p)));return zoom.call(this,p,...args)};return{panels:Reader.currentPanels,deck:Reader.turnPageMode?.book instanceof NthPageDeck};},comic);fs.writeFileSync(out+'/reader-initial.json',JSON.stringify(initial));console.log('current',initial.panels.length,'deck',initial.deck);assert.equal(initial.panels.length,5);
const ownership=await page.evaluate(frames=>frames.flatMap(f=>f.points.map(([x,y])=>({name:f.name,expected:f.owner,x,y,got:Reader.currentPanels.indexOf(Reader.findPanelAt(x/585,y/900))}))),qa.frames);console.log('ownership',ownership.length,ownership.filter(r=>r.expected!==r.got));assert(ownership.every(r=>r.expected===r.got));
const touches=[];for(const frame of qa.frames)for(let i=0;i<frame.points.length;i++){
 await page.evaluate(()=>Reader.resetZoom({animate:false}));await page.waitForTimeout(80);const [x,y]=frame.points[i];const pos=await page.evaluate(([x,y])=>{const r=Reader.getPanelImageContext().rect;return{x:r.left+x/585*r.width,y:r.top+y/900*r.height,n:captures.length}},[x,y]);await page.touchscreen.tap(pos.x,pos.y);await page.waitForFunction(n=>captures.length>n,pos.n,{timeout:20000});await page.waitForFunction(()=>Reader.panelOverlayActive&&!!Reader.els.panelOverlay?.querySelector('canvas'),null,{timeout:20000});
 const result=await page.evaluate(({owner,points})=>{const panel=captures.at(-1),original=Reader.currentPanels[owner],canvas=Reader.els.panelOverlay.querySelector('canvas'),meta=Reader.panelFocusMeta.panel;const q=p=>p._outline||p._quad||p._contours;return{same:JSON.stringify(q(panel))===JSON.stringify(q(original)),focusSame:JSON.stringify(q(meta))===JSON.stringify(q(original)),geometry:Reader.els.panelOverlay.dataset.geometry,size:[canvas.width,canvas.height],opaque:points.map(([x,y])=>{const X=Math.round((x/585-original.x)/original.w*canvas.width),Y=Math.round((y/900-original.y)/original.h*canvas.height);return canvas.getContext('2d').getImageData(X,Y,1,1).data[3];})};},{owner:frame.owner,points:frame.points});assert(result.same&&result.focusSame,JSON.stringify({frame,i,result}));assert(result.opaque.every(a=>a===255),JSON.stringify({frame,i,result}));touches.push({name:frame.name,x,y,...result});await page.waitForTimeout(300);if(!i)await page.screenshot({path:out+'/render-'+frame.name+'.png'});
}fs.writeFileSync(out+'/reader-report.json',JSON.stringify({ownership,touches,errors},null,2));console.log('PASS touches',touches.length,'errors',errors);assert.equal(errors.length,0);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
