'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../../..'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),map=fs.readFileSync(path.join(root,'js/panel-map-core.js'),'utf8'),gradle=fs.readFileSync(path.join(root,'android/app/build.gradle.kts'),'utf8');
assert(sw.includes('const CACHE_NAME = "nth-shelf-shell-2.79.138";'));
const block=sw.match(/const SHELL_FILES = \[([\s\S]*?)\];/);assert(block);const files=[...block[1].matchAll(/"([^"]+)"/g)].map(x=>x[1]);assert.equal(files.length,new Set(files).size);
for(const rel of ['./js/panels-chromatic-occlusion-cell.js','./js/panels-chromatic-inset-closure.js','./js/panels-round-atomic-inset.js','./js/panels-upper-paper-separation.js','./js/panels-page-edge-rail-cell.js','./js/panels-gutter-caption-boundary.js','./js/panels-gutter-ink-cap.js','./js/panels-gutter-tail-speech.js','./js/panels-excluded-speech.js','./js/panels-enclosure-remainder.js','./js/panels-ornate-ownership.js','./js/panels-ornate-inset.js','./js/panels-atomic-boundary-speech.js','./js/panels-detached-captions.js','./js/panels-saturated-terminal-cell.js','./js/panels-saturated-round-inset.js','./js/panels-saturated-rail-cell.js','./js/panels-saturated-frontier-cell.js','./js/panels-focused-paper-continuation.js','./js/panels-focused-paper-cell.js','./js/panels-high-contrast-enclosures.js','./js/panels-strong-continuation-groups.js','./js/panels-firm-enclosure-groups.js','./js/panels-continuation-enclosure-groups.js','./js/panels-contrast-enclosure-groups.js','./js/panels-dialogue-row-groups.js','./js/panels-color-enclosure-groups.js','./js/panels-short-row-speech.js','./js/panels-empty-enclosure-groups.js','./js/panels-gradient-residual-groups.js','./js/panels-neutral-matte-groups.js','./js/panels-stable-frontier-cells.js','./js/panels-trailing-edge-groups.js','./js/panels-paper-edge-groups.js','./js/panels-wide-paper-rows.js','./js/panels-paper-continuation-groups.js','./js/panels-landscape-upper-groups.js','./js/panels-landscape-cells.js','./js/panels-lateral-cell-completion.js','./js/panels-split-cell-completion.js','./js/panels-column-speech.js','./js/panels-long-tail-speech.js','./js/panels-tail-speech.js','./js/panels-dark-matte-completion.js','./js/panels-perimeter-consolidation.js','./js/panels-speech-ownership.js','./js/panels-gutter-split.js','./js/panels-crop-repair.js','./js/panels-lettering-cells.js','./js/panels-connected-pairs.js','./js/panels-neighbor-edge-cells.js','./js/panels-smooth-gutter-boundaries.js','./js/panels-interior-strokes.js','./js/panels-context-cells.js','./js/panels-local-boundary-consensus.js','./js/panels-horizontal-paper-strips.js','./js/panels-top-row-barrier.js','./js/panels-ragged-gutters.js','./js/panels-narrow-ink-frames.js']){assert(files.includes(rel));assert(fs.existsSync(path.join(root,rel)));}
assert(html.includes('<title>Nth Shelf 2.79.138 — Comic Reader</title>'));assert(html.includes('<meta name="application-version" content="2.79.138" />'));
assert(map.includes("MAP_VERSION: 'panel-map-exp-138'"));assert(map.includes("PROOF_VERSION: 'frame-proof-2.79.138'"));
assert(gradle.includes('versionCode = 28066'));assert(gradle.includes('versionName = "2.79.138"'));assert(gradle.includes('applicationIdSuffix = ".frametest138"'));assert(gradle.includes('"Nth Shelf Test138"'));
console.log(JSON.stringify({passed:true,cache:'nth-shelf-shell-2.79.138',shellFiles:files.length,horizontalPaperStrips:true,package:'frametest138'}));

const workflow=fs.readFileSync(path.join(root,".github/workflows/android-apk.yml"),"utf8");assert(workflow.includes("workflow_dispatch:"));assert(!/^  push:/m.test(workflow));
