'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');let cv;try{cv=require('@napi-rs/canvas');}catch(_){cv=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');}
// An indexed ancestor must remain ahead of its indexed descendants. Candidate
// overrides replace the source at that position; only missing modules append.
function orderedModuleCode(root,scripts,overrides={}){const indexed=new Set(scripts),files=scripts.map(name=>overrides[name]||path.resolve(root,name));for(const [name,file]of Object.entries(overrides))if(!indexed.has(name))files.push(file);return files.map(file=>fs.readFileSync(file,'utf8')).join('\n');}
function context(root=process.env.NTH_SHELF_SOURCE||path.resolve(__dirname,'../../..')){let canvasCount=0;const raf=[];function el(tag='div'){if(tag==='canvas')canvasCount++;const e=tag==='canvas'?cv.createCanvas(1,1):{};Object.assign(e,{children:[],style:{setProperty(k,v){this[k]=v}},dataset:{},setAttribute(){},appendChild(c){this.children.push(c);c.parentNode=this;},remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;},animate(frames,options){return this.animation={frames,options,cancel(){this.oncancel?.()}};}});const names=new Set();e.classList={add:n=>names.add(n),remove:n=>names.delete(n),toggle(n,on){if(on)names.add(n);else names.delete(n)},contains:n=>names.has(n)};return e;}
 const c=vm.createContext({console,setTimeout,clearTimeout,window:{},Image:cv.Image,ImageData:cv.ImageData,localStorage:{getItem:()=>null,setItem(){}},document:{createElement:el},requestAnimationFrame:fn=>raf.push(fn)}),scripts=[...fs.readFileSync(root+'/index.html','utf8').matchAll(/src="(js\/panels[^\"]*\.js)"/g)].map(m=>m[1]);const hardened=process.env.NTH_RAIL_CANDIDATE||path.resolve(root,'js/panels-page-edge-rail-cell.js'),candidate=process.env.NTH_CAPPED_RIM_CANDIDATE||(fs.existsSync(__dirname+'/panels-capped-rim-cell.js')?__dirname+'/panels-capped-rim-cell.js':root+'/js/panels-capped-rim-cell.js'),indexed=scripts.includes('js/panels-capped-rim-cell.js');let readerCode=fs.readFileSync(root+'/js/reader.js','utf8'),after='';
 if(indexed){const hooks=[...readerCode.matchAll(/\b(\w+)\.installReader\(Reader\)/g)].map(q=>q[1]),a=hooks.indexOf('PanelPageEdgeRailCell'),b=hooks.indexOf('PanelCappedRimCell');if(a<0||b<=a||hooks.filter(n=>n==='PanelCappedRimCell').length!==1)throw Error('The installed capped-rim guard must follow the page-edge guard.');}
 else{readerCode=readerCode.replace(/if\(typeof (?:PanelPageEdgeRailCell|PanelCappedRimCell)!==?'undefined'\)(?:PanelPageEdgeRailCell|PanelCappedRimCell)\.installReader\(Reader\);/g,'');after='\nPanelPageEdgeRailCell.installReader(Reader);PanelCappedRimCell.installReader(Reader);';}
 const moduleCode=orderedModuleCode(root,scripts,{'js/panels-page-edge-rail-cell.js':hardened,'js/panels-capped-rim-cell.js':candidate});vm.runInContext(moduleCode+'\n'+readerCode+after,c);const get=n=>vm.runInContext(n,c);return{get,cv,el,c,root,counters:()=>({canvases:canvasCount}),flush(){while(raf.length)raf.shift()();}};
}
const hash=c=>crypto.createHash('sha256').update(c.toBuffer('image/png')).digest('hex'),copy=x=>JSON.parse(JSON.stringify(x));
module.exports={context,orderedModuleCode,cv,hash,copy};
